### ISSUE TITLE
Typo in line 33

### ISSUE THREAD

**Issue by iyenokian** [Junkdnalab/acg_2023#2]
There is a type in the Jabberwacky.txt in the very last paragraph on the first line - line 33.

`coves` needs to be changed to `toves`

https://github.com/Junkdnalab/acg_2023/blob/716e9428a9f81f7b62b8daf58c37d3c65bc9c707/files/Jabberwacky.txt#LL33C32-L33C37

**Comment by dennishazelett** [comment]
Thank you, this error is now corrected.
