### ISSUE TITLE
Issue in line 3 of acg_2023/files /Jabberwacky.txt 

### ISSUE THREAD

**Issue by mazumdarn** [Junkdnalab/acg_2023#3]
The incorrect line is: "’Twas brillow, and the slimy coves"
The correct line should be: "’Twas brillig, and the slithy toves" 

https://github.com/Junkdnalab/acg_2023/blob/716e9428a9f81f7b62b8daf58c37d3c65bc9c707/files/Jabberwacky.txt#LL3C7-L3C14

**Comment by dennishazelett** [comment]
Thank you, the line is now corrected.
